name: 'word_app'
app_mode: 'debug'
mode: 'dev'
start_time: '2023-03-21'
machine_id: 46631
host_ip: "127.0.0.1" # 部署至云时记得更换，下同
port: 8080
log:
  level: 'debug'
  file_format: '2006-01-02'
  path: './logs'
  filename: 'woad_app'
  max_size: 200
  max_age: 30
  max_backups: 7
  compress: false
mysql:
  host: '127.0.0.1'
  port: 3306
  user: 'root'
  password: 'root'
  dbname: 'english_db'
  charset: 'utf8mb4'
  parseTime: true
  autoMigrate: false # 暂时关闭
  timeZone: 'Local'
  logLevel: 'info'
  max_open_cons: 200
  max_idle_cons: 10
  gorm:
    skipDefaultTx: true # 是否跳过默认事务
    tablePrefix: "" #表前缀
    singularTable: true # 是否使用单数表名(默认复数)，启用后，User结构体表将是user
    coverLogger: true # 是否覆盖默认logger
    prepareStmt: false # 执行任何SQL时都会创建一个prepared statement并将其缓存，以提高后续的效率
    disableForeignKeyConstraintWhenMigrating: true #在AutoMigrate 或 CreateTable 时，GORM 会自动创建外键约束，若要禁用该特性，可将其设置为 true
redis:
  host: '127.0.0.1'
  password: ''
  port: 6379
  db: 0
  pool_size: 100
jwt:
  secret: 'word.app'
  issuer: '林俊燃'
  subject: 'wordApp'
api_sms:
  app_code: ''
qq_email:
  username: ''
  secret: ''
refresh_db:
  username: 'backend'
  password: 'LJRljr109109'
